version: '2.4'
services:
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
    # user: "0:1001"
    # environment:
      # - PUID=0
      # - PGID=1001
    # restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql