version: '3.9'
services:
  postgresql:
    image: postgres
    environment:
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
      POSTGRES_PASSWORD: phishybank
      POSTGRES_USER: phishybank
      POSTGRES_DB: phishybank
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data